-- Copyright (c) 2024-2026 Testsmith. All rights reserved.
-- See LICENSE for details.

/*******************************************************************************
   Populate Tables
********************************************************************************/

/** Users **/
INSERT INTO `users` (`id`, `first_name`, `last_name`, `address`, `city`, `state`, `country`, `postcode`, `phone`, `dob`,
                     `email`, `password`, `role`)
VALUES (1, 'John', 'Doe', 'Test street 123', 'Utrecht', NULL, 'The Netherlands', NULL, NULL, '1980-01-01',
        'admin@practicesoftwaretesting.com', '9e2ed9cb4bf54a6b9dc4669a1d295466b2585c4346092bffb5333098431cd61d', 'admin'),
       (2, 'Jane', 'Doe', 'Test street 98', 'Vienna', NULL, 'Austria', NULL, NULL, '1980-02-02',
        'customer@practicesoftwaretesting.com', '9e2ed9cb4bf54a6b9dc4669a1d295466b2585c4346092bffb5333098431cd61d', 'user'),
       (3, 'Jack', 'Howe', 'Test street 654', 'Frankfurt', NULL, 'Germany', NULL, NULL, '1980-03-03',
        'customer2@practicesoftwaretesting.com', '9e2ed9cb4bf54a6b9dc4669a1d295466b2585c4346092bffb5333098431cd61d', 'user');

/** Brand names **/
INSERT INTO `brands` (`name`, `slug`)
VALUES ("Brand name 1", "brand-name-1"),
       ("Brand name 2", "brand-name-2"),
       ("Brand name 3", "brand-name-3"),
       ("Brand name 4", "brand-name-4"),
       ("Brand name 5", "brand-name-5"),
       ("Brand name 6", "brand-name-6"),
       ("Brand name 7", "brand-name-7"),
       ("Brand name 8", "brand-name-8"),
       ("Brand name 9", "brand-name-9"),
       ("Brand name 10", "brand-name-10");

/** Category names **/
INSERT INTO `categories` (`id`, `parent_id`, `name`, `slug`)
VALUES (1, null, "Hand Tools", "hand-tools"),
       (2, null, "Power Tools", "power-tools"),
       (3, 1, "Hammer", "hammer"),
       (4, 1, "Hand Saw", "hand-saw"),
       (5, 1, "Wrench", "wrench"),
       (6, 1, "Screwdriver", "screwdriver"),
       (7, 1, "Pliers", "pliers"),
       (8, 2, "Grinder", "grinder"),
       (9, 2, "Sander", "sander"),
       (10, 2, "Saw", "saw"),
       (11, 2, "Drill", "drill"),
       (12, null, "Other", "other");


/** Set of default images **/
INSERT INTO `product_images` (`id`, `by_name`, `by_url`, `source_name`, `source_url`,
                              `file_name`, `title`)
VALUES (1, "Helinton Fantin", "https://unsplash.com/@fantin", "Unsplash", "https://unsplash.com/photos/W8BNwvOvW4M",
        "pliers01.jpeg", "Combination pliers"),
       (2, "Everyday basics", "https://unsplash.com/@zanardi", "Unsplash", "https://unsplash.com/photos/I8eTuMmxIfo",
        "pliers02.jpeg", "Pliers"),
       (3, "Michael Dziedzic", "https://unsplash.com/@lazycreekimages", "Unsplash",
        "https://unsplash.com/photos/pM9pkc9J918", "pliers03.jpeg", "Bolt cutters"),
       (4, "Brett Jordan", "https://unsplash.com/@brett_jordan", "Unsplash", "https://unsplash.com/photos/GamuDTVm02g",
        "pliers04.jpeg", "Long nose pliers"),
       (5, "Yasin Hasan", "https://unsplash.com/@yasin", "Unsplash", "https://unsplash.com/photos/dwlxTSpfKXg",
        "pliers05.jpeg", "Slip joint pliers"),
       (6, "iMattSmart", "https://unsplash.com/@imattsmart", "Unsplash", "https://unsplash.com/photos/jaLaLQdkBOE",
        "hammer01.jpeg", "Claw Hammer"),
       (7, "Jozsef Hocza", "https://unsplash.com/@hocza", "Unsplash", "https://unsplash.com/photos/D3nouOYbALc",
        "hammer02.jpeg", "Hammer"),
       (8, "Andrew George", "https://unsplash.com/@andrewjoegeorge", "Unsplash",
        "https://unsplash.com/photos/YU2mCvXR0wA", "hammer03.jpeg", "Claw Hammer"),
       (9, "ANIRUDH", "https://unsplash.com/@lanirudhreddy", "Unsplash", "https://unsplash.com/photos/3esjG-nlgyk",
        "hammer04.jpeg", "Hammer"),
       (10, "Fausto Marqués", "https://unsplash.com/@faustomarques", "Unsplash",
        "https://unsplash.com/photos/A9dq-L3zzHA", "hammer05.jpeg", "Hammer"),
       (11, "Jonny Gios", "https://unsplash.com/@supergios", "Unsplash", "https://unsplash.com/photos/ARaYGFeuwpU",
        "hammer06.jpeg", "Claw Hammer"),
       (12, "Wesley Tingey", "https://unsplash.com/@wesleyphotography", "Unsplash",
        "https://unsplash.com/photos/9z9fxr_7Z-k", "hammer07.jpeg", "Hammer"),
       (13, "Jonathan Cooper", "https://unsplash.com/@theshuttervision", "Unsplash",
        "https://unsplash.com/photos/fTpzd-PjyDQ", "saw01.jpeg", "Wood Saw"),
       (14, "Recha Oktaviani", "https://unsplash.com/@rechaoktaviani", "Unsplash",
        "https://unsplash.com/photos/t__61ap00Mc", "wrench01.jpeg", "Adjustable wrench"),
       (15, "Tekton", "https://unsplash.com/@tekton_tools", "Unsplash", "https://unsplash.com/photos/9z7t48S5C_g",
        "wrench02.jpeg", "Wrench"),
       (16, "Akshat Swaminath", "https://unsplash.com/@akshat_swaminath", "Unsplash",
        "https://unsplash.com/photos/hg34mNWFRaI", "wrench03.jpeg", "Open-end spanners (Set)"),
       (17, "Tekton", "https://unsplash.com/@tekton_tools", "Unsplash", "https://unsplash.com/photos/jlY6nV_STIw",
        "screwdriver01.jpeg", "Phillips Screwdriver"),
       (18, "Everyday basics", "https://unsplash.com/@zanardi", "Unsplash", "https://unsplash.com/photos/a6LO3iO5AIk",
        "screwdriver02.jpeg", "Screwdriver"),
       (19, "subvertivo _lab", "https://unsplash.com/@subvertivo_lab", "Unsplash",
        "https://unsplash.com/photos/G6yracEEm8A", "sander01.jpeg", "Sheet sander"),
       (20, "Luther.M.E. Bottrill", "https://unsplash.com/@luthermeb", "Unsplash",
        "https://unsplash.com/photos/7kHN1-9dD_4", "sander02.jpeg", "Belt sander"),
       (21, "Luther.M.E. Bottrill", "https://unsplash.com/@luthermeb", "Unsplash",
        "https://unsplash.com/photos/EgIT3YHBo9E", "saw02.jpeg", "Saw"),
       (22, "Adi Goldstein", "https://unsplash.com/@adigold1", "Unsplash", "https://unsplash.com/photos/aO4c6o4H2MI",
        "sander03.jpeg", "Random orbit sander"),
       (23, "Syed Hussaini", "https://unsplash.com/@syhussaini", "Unsplash", "https://unsplash.com/photos/MXeDE_yCdHQ",
        "drill01.jpeg", "Cordless Drill"),
       (24, "NeONBRAND", "https://unsplash.com/@neonbrand", "Unsplash", "https://unsplash.com/photos/CuDoRFyTkAQ",
        "drill02.jpeg", "Cordless Drill"),
       (25, "Jonathan Cooper", "https://unsplash.com/@theshuttervision", "Unsplash",
        "https://unsplash.com/photos/7sZwThSntdw", "drill03.jpeg", "Cordless Drill 18V"),
       (26, "Manik Roy", "https://unsplash.com/@pixnum", "Unsplash", "https://unsplash.com/photos/_UGTrlvki_A",
        "drill04.jpeg", "Cordless Drill"),
       (27, "Ade Adebowale", "https://unsplash.com/@adebowax", "Unsplash", "https://unsplash.com/photos/DKr6BEdI2sE",
        "crane01.jpg", "Crane"),
       (28, "John Kakuk", "https://unsplash.com/@mgnfy", "Unsplash", "https://unsplash.com/photos/HvvPceHYLOg",
        "excavator01.jpg", "Excavator"),
       (29, "Zac Edmonds", "https://unsplash.com/@zacedmo", "Unsplash", "https://unsplash.com/photos/N1LBcqLP9ec",
        "bulldozer01.jpg", "Bulldozer");


INSERT INTO `products` (`id`, `name`, `description`, `stock`, `price`, `brand_id`, `category_id`, `product_image_id`, `is_location_offer`, `is_rental`, `co2_rating`)
VALUES (1, "Combination Pliers",
        "Versatile combination pliers designed for gripping, bending, and cutting wire with ease. Featuring chrome vanadium steel construction with induction-hardened cutting edges, these pliers deliver excellent grip and leverage for a wide range of tasks. The precision-machined jaws combine flat gripping surfaces with a pipe-grip section and integrated wire cutter for true multi-purpose functionality. Ergonomic bi-component handles reduce hand fatigue during extended use and provide a secure hold even with oily or gloved hands. The joint is precisely fitted to eliminate play and ensure smooth operation over thousands of cycles. Ideal for electricians, mechanics, and DIY enthusiasts tackling everyday projects around the workshop or job site.",
        11, 14.15, 1, 7, 1, 0, 0, 'D'),
       (2, "Pliers",
        "Reliable general-purpose pliers crafted from drop-forged carbon steel for long-lasting durability in demanding working conditions. The serrated jaws provide a firm grip on a variety of materials including wire, nails, small fasteners, and irregularly shaped objects. Comfortable rubber-coated handles absorb vibration and reduce hand fatigue during extended use, while the non-slip surface ensures confident handling. The precision pivot joint maintains alignment under load, delivering smooth, controlled jaw action with every squeeze. Heat-treated steel construction resists wear and deformation even under heavy use. A must-have foundational tool for any workshop, equally suited for professional tradespeople and home repair projects.",
        11, 12.01, 1, 7, 2, 0, 0, 'D'),
       (3, "Bolt Cutters",
        "Heavy-duty bolt cutters engineered to slice through hardened bolts, chains, padlocks, and wire fencing with minimal effort. The compound leverage mechanism multiplies your cutting force by a factor of 30, enabling clean cuts through materials up to 10mm in diameter. Hardened alloy steel blades are precisely ground and heat-treated to maintain a sharp edge through years of repeated use on tough materials. Ergonomic rubber grips and the generous 750mm handle length provide excellent control, leverage, and reach during overhead or awkward-angle cuts. An adjustable blade tension screw lets you fine-tune the jaw alignment for optimal cutting performance. Built for demolition crews, locksmiths, fencing contractors, and maintenance professionals who need reliable cutting power day after day.",
        11, 48.41, 2, 7, 3, 1, 0, 'D'),
       (4, "Long Nose Pliers",
        "Precision long nose pliers with narrow tapered jaws designed for reaching into tight, confined spaces and bending fine wire with accuracy. Made from chrome vanadium steel with induction-hardened cutting edges that cleanly sever copper, brass, and steel wire without crushing or fraying. The slim jaw profile tapers to a fine point, making these pliers indispensable for electrical terminal work, jewelry making, and intricate mechanical repairs. Bi-component comfort grips minimize hand strain during detailed tasks requiring a steady hand and controlled pressure. The leaf-spring joint returns the handles to the open position automatically, speeding up repetitive tasks. A must-have precision tool trusted by electricians, electronics technicians, and hobbyists worldwide.",
        0, 14.24, 1, 7, 4, 0, 0, 'D'),
       (5, "Slip Joint Pliers",
        "Adjustable slip joint pliers that feature a two-position pivot mechanism for switching between regular and wide jaw openings to accommodate different fastener sizes. The PVC-coated handles offer a comfortable, non-slip grip while the precisely machined jaws securely grasp round, flat, and hexagonal objects without slipping. Constructed from durable drop-forged carbon steel that has been heat-treated to withstand heavy daily use in professional environments. The curved jaw section grips pipes and cylindrical objects, while the flat front surface handles nuts, bolts, and sheet materials. A wire cutter integrated near the pivot handles light cutting tasks without reaching for a separate tool. Perfect for plumbing, automotive, HVAC, and general maintenance work where a single versatile gripping tool saves time.",
        11, 9.17, 2, 7, 5, 0, 0, 'D'),
       (6, "Claw Hammer with Shock Reduction Grip",
        "Ergonomic claw hammer featuring an advanced shock reduction grip system that absorbs up to 70% of impact vibrations, protecting your wrist, elbow, and shoulder during prolonged nailing sessions. The 450g carbon steel head is precision-balanced and heat-treated for maximum hardness, ensuring accurate nail driving with minimal effort on every swing. The curved claw design effortlessly removes nails without damaging surrounding wood surfaces, making it equally useful for construction and renovation work. A fiberglass-reinforced handle combines lightweight strength with exceptional durability that far outlasts traditional wooden handles. The overmolded soft-grip zone conforms to your hand shape for a custom-feeling, fatigue-free hold throughout long working days. Recommended for professional framing, carpentry, and renovation projects where operator comfort matters as much as striking performance.",
        11, 13.41, 1, 3, 6, 1, 0, 'D'),
       (7, "Hammer",
        "A dependable standard claw hammer suitable for driving and removing nails in everyday construction, carpentry, and home improvement projects. The 350g carbon steel head is drop-forged and heat-treated for maximum hardness, then fitted to a traditional wooden handle that provides natural shock absorption with each strike. Well-balanced weight distribution between the head and handle ensures accurate strikes with minimal wrist effort, reducing fatigue during repetitive nailing tasks. The polished face resists rust and provides a smooth surface that drives nails cleanly without leaving marks on finish materials. A gently curved claw provides reliable nail extraction leverage without excessive force. This versatile hammer belongs in every toolbox, from professional carpentry workshops to home garages and apartment maintenance kits.",
        11, 12.58, 1, 3, 7, 0, 0, 'D'),
       (8, "Claw Hammer",
        "Traditional claw hammer with a polished carbon steel head engineered for driving and removing nails with precision and confidence. The rubber-wrapped handle provides a secure, comfortable grip even in wet, dusty, or cold conditions where bare metal or wood handles would slip. At 500g, it offers the ideal balance between striking power and maneuverability for general carpentry, framing, and construction tasks. The curved claw design allows for smooth nail extraction without gouging or marring wood surfaces, protecting your finished work. The head-to-handle connection uses an epoxy-bonded wedge system that prevents loosening over time. A reliable, no-nonsense tool that professional carpenters and weekend builders alike reach for every day.",
        11, 11.48, 1, 3, 8, 1, 0, 'D'),
       (9, "Thor Hammer",
        "The legendary Thor Hammer combines premium craftsmanship with raw striking power in a tool that is truly built to last generations. Forged from Uru metal with a hand-wrapped leather grip, this extraordinary 5kg masterpiece delivers unmatched impact force for the most demanding demolition, forging, and heavy construction tasks. The perfectly balanced oversized head ensures every swing transfers maximum energy to the target, while the enlarged striking face covers more surface area than any conventional hammer. Despite its impressive mass, the ergonomic handle design and precise weight distribution allow for surprisingly controlled, accurate swings. This is not merely a tool but a statement piece for those who accept nothing less than the absolute best in their workshop. Comes with a lifetime warranty because true legends never fade. Please note: only one Thor Hammer is permitted per customer.",
        11, 11.14, 1, 3, 9, 0, 0, 'D'),
       (10, "Sledgehammer",
        "Powerful sledgehammer designed for heavy demolition, driving stakes, breaking concrete, and splitting masonry with devastating efficiency. The 3.6kg forged steel head delivers tremendous impact force concentrated through a hardened striking face that resists chipping and mushrooming. A 900mm fiberglass handle provides excellent shock absorption, superior reach, and the flexibility needed to generate maximum swing velocity. Anti-vibration technology embedded in the handle dampens recoil forces, significantly reducing operator fatigue during extended demolition sessions. The overmolded grip zone prevents the handle from twisting or slipping out of sweaty or gloved hands during overhead swings. Built for construction workers, landscapers, and demolition crews who demand professional-grade striking tools that perform reliably under the most punishing conditions.",
        11, 17.75, 1, 3, 10, 0, 0, 'D'),
       (11, "Claw Hammer with Fiberglass Handle",
        "Modern claw hammer featuring a durable fiberglass handle that outlasts wood, absorbs vibration more effectively, and shrugs off moisture without swelling, cracking, or loosening over time. The 400g carbon steel head is drop-forged and heat-treated to optimal hardness for reliable nail driving in softwood, hardwood, and engineered lumber. The fiberglass core is permanently bonded to the head and encased in a comfortable overmold grip that prevents slipping even when wet or oily. A magnetic nail starter near the head allows one-handed nail placement, freeing your other hand to hold materials in position. The curved claw provides smooth, controlled nail extraction with excellent leverage. Ideal for contractors and DIY builders who want a weather-resistant, maintenance-free hammer that performs reliably on every job site and in any season.",
        11, 20.14, 1, 3, 11, 0, 0, 'D'),
       (12, "Court Hammer",
        "Compact precision court hammer with a 300g carbon steel head designed for light-duty nailing, tapping dowels, and delicate assembly tasks where a full-size hammer would be too heavy and unwieldy. The short 280mm wooden handle provides excellent close-quarters control for detailed work in confined spaces such as cabinets, closets, and furniture interiors. The polished flat face drives small nails and brads without bending them, while the cross-peen on the opposite side is useful for starting small fasteners between your fingers. Perfectly weighted to provide enough force for trim carpentry and light framing without damaging delicate surfaces. The lacquered wooden handle resists moisture absorption and provides a warm, comfortable grip. A handy addition to any toolkit when precision and finesse matter more than raw striking power.",
        11, 18.63, 1, 3, 12, 1, 0, 'D'),
       (13, "Wood Saw",
        "Traditional hand saw crafted with a high carbon steel blade featuring 7 teeth per inch for efficient crosscutting and ripping of timber, plywood, and composite boards. The 500mm blade length handles standard dimensional lumber, sheet goods, and tree branches with smooth, clean cuts that require minimal sanding afterward. Each tooth is precision-set and hardened to stay sharp through hundreds of cuts in both softwood and hardwood species. A comfortable contoured wooden handle provides a secure three-finger grip and natural wrist alignment that reduces fatigue during extended cutting sessions. The taper-ground blade is thinner at the back than at the teeth, reducing friction and binding during deep cuts. Essential for carpenters, woodworkers, and gardeners who appreciate the precision, quiet operation, and portability of a quality hand saw.",
        11, 12.18, 1, 4, 13, 0, 0, 'B'),
       (14, "Adjustable Wrench",
        "Chrome vanadium steel adjustable wrench with a smooth-action worm gear jaw mechanism that opens to a generous 30mm capacity for versatile bolt, nut, and fitting work. The precision-machined worm gear ensures the movable jaw stays firmly locked in position under heavy torque loads, eliminating the slipping and rounding common with lesser tools. Laser-etched metric and imperial scales on the jaw face allow for quick size identification without a separate caliper or ruler. The slim-profile head design fits into recessed areas and tight clearances where a standard box wrench cannot reach. A corrosion-resistant chrome finish protects against rust and makes the wrench easy to wipe clean after greasy jobs. A workshop essential for plumbers, mechanics, and assembly technicians who work with multiple fastener sizes throughout the day.",
        11, 20.33, 1, 5, 14, 0, 0, 'D'),
       (15, "Angled Spanner",
        "Offset angled spanner specifically designed to reach bolts, nuts, and fittings in recessed, obstructed, or deeply set locations where a straight wrench simply cannot fit or turn. Made from chrome vanadium steel with a satin-chrome finish for excellent corrosion resistance, easy cleaning, and professional appearance. The 15-degree offset angle at both ends provides ample knuckle clearance while maintaining full torque transfer to the fastener without slipping. By flipping the spanner over between turns, you can work in spaces with as little as 30 degrees of swing arc. The slim jaw profile fits into narrow gaps alongside adjacent components without interference. Indispensable for automotive mechanics working in engine bays, appliance repair technicians accessing internal components, and industrial maintenance engineers servicing tightly packed machinery.",
        11, 14.14, 1, 5, 15, 1, 0, 'D'),
       (16, "Open-end Spanners (Set)",
        "Complete professional set of 12 open-end spanners covering metric sizes from 6mm to 32mm, crafted from chrome vanadium steel for lasting strength and resistance to flexing under heavy torque. Each spanner features a slim-profile head design angled at 15 degrees for access in tight spaces, and the open-end configuration allows quick lateral placement on fasteners without the need to thread them through from the end. A mirror-polished chrome finish resists corrosion, repels grease and oil, and looks sharp in any professional tool collection. Size markings are deeply laser-etched on both sides of each spanner for instant identification even in low light conditions. The set is supplied in a durable roll-up canvas pouch with individual pockets for organized storage and easy transport to any job site. An essential investment for automotive workshops, industrial maintenance departments, and serious home mechanics.",
        11, 38.51, 1, 5, 16, 0, 0, 'D'),
       (17, "Phillips Screwdriver",
        "Professional-quality Phillips screwdriver with a PH2 tip precision-machined from chrome vanadium steel and vapor-blasted for maximum grip inside cross-head screw recesses. The bi-component handle features a soft-grip comfort zone that absorbs torque reaction and vibration, combined with a hard polypropylene core that transmits maximum turning force to the blade. A hex bolster machined into the shaft just above the handle allows a wrench to be applied for additional turning leverage on stubborn or over-tightened screws. The round blade shaft is chrome-plated for corrosion resistance and easy cleaning after use in greasy or painted environments. A hanging hole in the handle allows convenient pegboard or hook storage for quick identification and access. Suitable for electricians, cabinet makers, assembly technicians, and anyone who needs a reliable, comfortable everyday screwdriver.",
        11, 4.92, 1, 6, 17, 1, 0, 'C'),
       (18, "Mini Screwdriver",
        "Precision mini screwdriver with a PH0 tip designed specifically for working with small screws found in electronics, eyeglasses, watches, camera equipment, and detailed hobby projects. The carbon steel blade is hardened and tempered to maintain an accurate tip profile through thousands of insertions in delicate threaded fasteners. A freely rotating end cap allows single-handed operation by applying downward pressure with your index finger while your thumb and middle finger turn the barrel. The knurled aluminum barrel provides a secure, non-slip grip for fine adjustments requiring minimal torque. At just 150mm overall length, this screwdriver fits easily in a shirt pocket, precision tool roll, or electronics repair kit. An essential tool for IT technicians, jewelers, model builders, and anyone who works with miniature components.",
        11, 13.96, 1, 6, 18, 0, 0, 'C'),
       (19, "Sheet Sander",
        "Electric sheet sander delivering 12,000 orbits per minute for fast, controlled surface finishing on wood, painted surfaces, metal, and composite materials. The 240W motor provides consistent sanding power from rough 60-grit material removal through to ultra-fine 240-grit finishing, all using standard 112x102mm sanding sheets that are widely available and economical. An integrated dust collection port connects directly to a shop vacuum for a virtually dust-free work environment, or the included cloth dust bag captures fine particles when vacuum extraction is not available. The paper clamping system accepts both pre-punched and plain sanding sheets, giving you maximum flexibility in abrasive selection. At just 1.8kg, this sander is light enough for extended one-handed use on vertical surfaces, overhead work, and detailed finishing tasks. Low vibration levels and an ergonomic palm-grip design reduce hand fatigue, making this tool a pleasure to use for beginners and professionals alike.",
        11, 58.48, 1, 9, 19, 0, 0, 'E'),
       (20, "Belt Sander",
        "Powerful 800W belt sander engineered for aggressive material removal on large flat surfaces including tabletops, doors, hardwood flooring, and timber decking. The 76x533mm sanding belt travels at an impressive 380 meters per minute, enabling rapid stock removal, paint stripping, and surface leveling in a fraction of the time required by orbital sanders. A precision front roller nose allows flush sanding against walls, inside corners, and perpendicular surfaces for complete coverage without leaving unsanded edges. The quick-release belt change mechanism allows swapping abrasive grits in seconds without tools, keeping workflow interruptions to a minimum. A secondary handle on the front provides two-handed control and even pressure distribution across the full width of the belt. The dust extraction bag and auxiliary vacuum port work together to capture the large volume of fine particles generated during aggressive sanding operations.",
        11, 73.59, 1, 9, 20, 0, 0, 'E'),
       (21, "Circular Saw",
        "Portable circular saw powered by a robust 1400W motor that drives a 190mm carbide-tipped blade at 5,500 RPM for clean, fast, straight cuts through solid timber, plywood, MDF, and sheet materials up to 67mm thick. The precision-machined aluminum base plate provides a flat, stable reference surface and adjusts smoothly for bevel cuts from 0 to 45 degrees with a positive detent at the most commonly used angles. An integrated dust blower directs a stream of air ahead of the blade to keep the pencil line visible under the constant shower of sawdust generated during cutting. The spindle lock allows quick, safe blade changes with a single wrench, while the electric brake stops the blade within seconds of releasing the trigger for added safety between cuts. An ergonomic soft-grip main handle and auxiliary front handle provide confident two-handed control for both plunge cuts and guided rip cuts. Essential for framing carpenters, renovation contractors, and DIY builders who need a portable, powerful saw for on-site timber work.",
        11, 80.19, 1, 10, 21, 0, 0, 'D'),
       (22, "Random Orbit Sander",
        "Electric random orbit sander combining 14,000 RPM pad rotation with an eccentric 2.5mm orbital action pattern that produces a completely swirl-free finish on wood, lacquer, paint, and primer surfaces. The 125mm hook-and-loop pad accepts standard multi-hole sanding discs from 60 to 400 grit for quick, tool-free abrasive changes between roughing and finishing passes. A responsive 300W motor delivers consistent sanding power at every speed setting, from aggressive stock removal at full speed to delicate final finishing at reduced RPM using the variable speed dial. The random orbital motion means no two particles of abrasive ever follow the same path twice, eliminating the visible scratch patterns that plague standard orbital and belt sanders. The integrated micro-filter dust collection system captures over 90% of airborne particles at the source. Low vibration levels and an ergonomic palm-grip body make this the preferred finishing tool for furniture makers, cabinet shops, and automotive paint preparation.",
        11, 100.79, 1, 9, 22, 0, 0, 'E'),
       (23, "Cordless Drill 20V",
        "Versatile 20V cordless drill and driver featuring a high-capacity 4.0Ah lithium-ion battery that delivers sustained power for a full day of demanding drilling and fastening tasks on a single charge. The heavy-duty 13mm single-sleeve keyless chuck accepts a comprehensive range of drill bits, spade bits, hole saws, and driver accessories without the need for a chuck key. A two-speed all-metal gearbox provides 450 RPM in low gear for maximum torque fastening and 1,800 RPM in high gear for rapid drilling in wood, metal, and masonry materials. Twenty-plus-one torque settings on the adjustable clutch collar allow precise control over fastening depth to prevent cam-out and screw damage in different materials. An integrated LED work light automatically illuminates the drilling area when the trigger is touched, providing visibility in dark cabinets, ceiling cavities, and crawl spaces. Ideal for contractors, remodelers, and serious DIY enthusiasts who need portable, professional-grade power without being tethered to an extension cord.",
        11, 125.23, 1, 11, 23, 1, 0, 'B'),
       (24, "Cordless Drill 24V",
        "Professional-grade 24V cordless drill delivering an impressive 80Nm of peak torque through a heavy-duty all-metal two-speed gearbox designed for the most demanding commercial drilling and fastening applications. The 5.0Ah high-capacity lithium-ion battery provides extended runtime that gets professional users through a full working day of continuous drilling, driving, and impacting without interruption. A 13mm all-metal single-sleeve keyless chuck ensures reliable, concentric bit retention even under the high torque loads generated during large-diameter drilling and long fastener driving. Twenty-plus-one clutch torque settings provide precise depth and torque control across the full range of materials from delicate cabinetry to structural timber framing. The brushless motor technology extends tool life, increases runtime, and generates less heat than brushed alternatives under sustained heavy loads. Built for trade professionals in construction, electrical, plumbing, and HVAC who demand maximum performance, durability, and battery endurance from their primary cordless tool.",
        11, 66.54, 1, 11, 24, 0, 0, 'B'),
       (25, "Cordless Drill 18V",
        "Compact and lightweight 18V cordless drill offering 50Nm of torque in a well-balanced package that reduces operator fatigue during extended overhead, horizontal, and downward drilling and driving tasks. The 3.0Ah lithium-ion battery provides ample capacity for a busy day of residential drilling and driving, while the fast charger replenishes a depleted battery in under 60 minutes. A 10mm keyless chuck handles the most commonly used drill bits, spade bits, and quarter-inch hex driver inserts for everyday workshop and job site tasks. The ergonomic soft-grip handle and compact head length provide comfortable, controlled operation in tight spaces where larger drills cannot reach. An integrated LED work light illuminates the work surface for improved accuracy when driving screws in dimly lit areas. A great all-around cordless drill for home improvement, furniture assembly, deck building, and light-duty trade work where portability and comfort are priorities.",
        11, 119.24, 1, 11, 25, 0, 0, 'B'),
       (26, "Cordless Drill 12V",
        "Lightweight 12V cordless drill perfect for light-duty drilling, screw driving, and assembly tasks in wood, drywall, plastic, and thin sheet metal. The ultra-compact design weighs just 1.2kg with the 2.0Ah battery installed, making it exceptionally easy to maneuver and control in tight spaces like inside cabinets, closets, junction boxes, and overhead ceiling cavities where heavier drills cause premature fatigue. The tool delivers up to 30Nm of torque through a 10mm keyless chuck, providing adequate power for the vast majority of household and light commercial fastening applications. Fifteen-plus-one clutch torque positions give you precise control over fastening depth and prevent over-tightening in delicate materials like softwood trim and melamine shelving. A quick-charging system brings the battery from empty to full in approximately 45 minutes, minimizing downtime between tasks. An excellent first cordless drill for homeowners, apartment dwellers, and hobbyists, and a convenient secondary tool for professionals who want a light, compact option alongside their heavy-duty driver.",
        11, 46.50, 1, 11, 26, 1, 0, 'B'),
       (27, "Excavator",
        "Heavy-duty tracked excavator available for hourly rental, designed for professional foundation digging, trenching, utility installation, and general earthmoving operations on residential and commercial construction sites. The powerful hydraulic system delivers smooth, responsive boom, arm, and bucket controls for precise positioning and efficient material handling in both tight urban spaces and open excavation sites. An enclosed climate-controlled cab provides operator comfort during long shifts, with excellent forward, side, and rear visibility through large laminated safety-glass windows and an integrated rearview camera system. The rubber-tracked undercarriage minimizes ground disturbance on finished surfaces while providing stable, sure-footed mobility on slopes, soft ground, and uneven terrain. Quick-coupling hydraulic connections allow rapid attachment changes between digging buckets, grading blades, and hydraulic breakers without leaving the cab. Suitable for projects ranging from swimming pool excavation and basement digging to municipal utility trenching and site grading operations.",
        null, 136.50, 1, 12, 28, 1, 1, 'E'),
       (28, "Bulldozer",
        "Robust tracked bulldozer available for hourly rental, built for heavy-duty grading, site clearing, land leveling, and large-volume earthmoving operations on construction and infrastructure projects. The wide-blade dozer pushes enormous volumes of soil, sand, gravel, and debris with ease, while the optional rear-mounted ripper attachment fractures compacted ground, asphalt, and embedded tree roots ahead of the blade pass. Ergonomic joystick cab controls and a fully automatic hydrostatic transmission allow operators of all experience levels to work efficiently and precisely from the first hour of rental. The enclosed cab features climate control, a suspension seat, and panoramic visibility for comfortable, fatigue-free operation during extended shifts. Integrated GPS rough-grading guidance is available as an optional add-on for projects requiring precise elevation control. Ideal for subdivision site preparation, road subgrade construction, agricultural land reclamation, and large-scale commercial landscaping projects.",
        null, 147.50, 1, 12, 29, 1, 1, 'E'),
       (29, "Crane",
        "Mobile hydraulic crane available for hourly rental, purpose-engineered for lifting, positioning, and placing heavy loads on active construction sites, industrial facilities, and infrastructure projects. The multi-section telescoping boom extends smoothly to reach elevated installation positions while the four-point hydraulic outrigger system provides a rock-solid, perfectly level base on uneven, sloped, or soft terrain. The precision proportional load control system allows millimeter-accurate positioning of suspended loads, while the rated capacity indicator and automatic overload cutoff ensure every lift is performed safely within the machines certified working limits. The fully enclosed operators cab features ergonomic controls, climate management, and unobstructed boom-tip visibility for confident operation in all weather conditions. Extensive safety systems including anti-two-block, swing-limit, and wind-speed monitoring protect both the operator and surrounding workers on busy sites. Perfect for structural steel erection, precast concrete placement, HVAC rooftop installation, and any material handling task that exceeds the reach or capacity of standard jobsite equipment.",
        null, 153.50, 1, 12, 27, 1, 1, 'E');

INSERT INTO `favorites` (`id`, `user_id`, `product_id`)
VALUES (1, 2, 1),
       (2, 2, 5),
       (3, 2, 20);

INSERT INTO `invoices` (`id`, `user_id`, `invoice_date`, `invoice_number`, `billing_address`, `billing_city`, `billing_state`,
                        `billing_country`, `billing_postcode`, `total`, `payment_method`, `payment_account_name`,
                        `payment_account_number`, `created_at`)
VALUES (1, 2, '2019-04-05 22:04:47', 'INV-2019000001', 'Test street 123', 'Utrecht', 'Utrecht', 'The Netherlands', '1122AB', '34.04',
        'Cash on Delivery', 'Tester', '09876543ABC', NOW()),
       (2, 2, '2020-07-16 22:04:47', 'INV-2020000001', 'Test street 123', 'Utrecht', 'Utrecht', 'The Netherlands', '1122AB', '34.47',
        'Cash on Delivery', 'Tester', '09876543ABC', NOW()),
       (3, 2, '2020-03-20 22:04:47', 'INV-2020000002', 'Test street 123', 'Utrecht', 'Utrecht', 'The Netherlands', '1122AB', '16.14',
        'Cash on Delivery', 'Tester', '09876543ABC', NOW()),
       (4, 2, '2021-09-25 22:04:47', 'INV-2021000001', 'Test street 123', 'Brussels', 'Brussels', 'Belgium', '1122AB', '19.24',
        'Bank Transfer', 'Tester', '09876543ABC', NOW()),
       (5, 2, '2021-10-30 22:04:47', 'INV-2021000002', 'Test street 123', 'Brussels', 'Brussels', 'Belgium', '1122AB', '27.11',
        'Cash on Delivery', 'Tester', '09876543ABC', NOW()),
       (6, 2, NOW() - INTERVAL 3 DAY, 'INV-2022000001', 'Test street 123', 'Utrecht', 'Utrecht', 'The Netherlands', '1122AB', '20.14',
        'Cash on Delivery', 'Tester', '09876543ABC', NOW()),
       (7, 2, NOW() - INTERVAL 1 DAY, 'INV-2022000002', 'Test street 123', 'Utrecht', 'Utrecht', 'The Netherlands', '1122AB', '22.66',
        'Cash on Delivery', 'Tester', '09876543ABC', NOW()),
       (8, 3, '2021-10-30 22:04:47', 'INV-2021000003', 'Midway Road 123', 'Springdale', 'Arkansas', 'United States', '72764', '27.11',
        'Cash on Delivery', 'Tester', '09876543ABC', NOW()),
       (9, 3, NOW() - INTERVAL 3 DAY, 'INV-2022000003', 'Midway Road 123', 'Springdale', 'Arkansas', 'United States', '72764', '20.14',
        'Cash on Delivery', 'Tester', '09876543ABC', NOW()),
       (10, 3, NOW() - INTERVAL 1 DAY, 'INV-2022000004', 'Midway Road 123', 'Springdale', 'Arkansas', 'United States', '72764', '22.66',
        'Cash on Delivery', 'Tester', '09876543ABC', NOW());


INSERT INTO `invoice_items` (`invoice_id`, `product_id`, `unit_price`, `quantity`, `created_at`)
VALUES (1, 3, '8.41', 1, NOW()),
       (1, 1, '14.15', 1, NOW()),
       (1, 8, '11.48', 1, NOW()),

       (2, 14, '20.33', 1, NOW()),
       (2, 15, '14.14', 1, NOW()),

       (3, 18, '13.96', 1, NOW()),
       (3, 13, '2.18', 1, NOW()),

       (4, 25, '19.24', 1, NOW()),

       (5, 21, '10.19', 1, NOW()),
       (5, 10, '7.75', 1, NOW()),
       (5, 5, '9.17', 1, NOW()),

       (6, 11, '20.14', 1, NOW()),

       (7, 1, '14.15', 1, NOW()),
       (7, 16, '8.51', 1, NOW()),

       (8, 21, '10.19', 1, NOW()),
       (8, 10, '7.75', 1, NOW()),
       (8, 5, '9.17', 1, NOW()),

       (9, 11, '20.14', 1, NOW()),

       (10, 1, '14.15', 1, NOW()),
       (10, 16, '8.51', 1, NOW());
