version: '2'
services:
  laravel-api:
    image: testsmith/practice-software-testing-${SPRINT}-api
    environment:
      - "PHP_OPCACHE_VALIDATE_TIMESTAMPS=1"
      - "DB_PORT=3306"
      - "DB_HOST=mariadb"
      - "host=localhost"
      - DISABLE_LOGGING=${DISABLE_LOGGING}
    volumes:
      - laravel-app-code:/var/www

  angular-ui:
    image: testsmith/practice-software-testing-${SPRINT}-ui
    ports:
      - 4200:4200
    command: >
      bash -c "ng serve --host 0.0.0.0 --port 4200"

  # The Web Server
  web:
    image: testsmith/practice-software-testing-web
    ports:
      - 8091:80
      - 8000:81
    depends_on:
      - laravel-api

  cron:
    image: testsmith/practice-software-testing-cron
    restart: always
    depends_on:
      - mariadb
      - laravel-api
    volumes:
      - laravel-app-code:/var/www
    working_dir: /var/www
    command: sh -c "crond -f -l 8"
    environment:
      - "PHP_OPCACHE_VALIDATE_TIMESTAMPS=1"
      - "DB_PORT=3306"
      - "DB_HOST=mariadb"
      - "host=localhost"
      - DISABLE_LOGGING=${DISABLE_LOGGING}

  mariadb:
    image: yobasystems/alpine-mariadb:10.6.11
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: toolshop

volumes:
  laravel-app-code:
