// Runs before ng build / ng serve to stamp version info into src/environments/version.ts
const { execSync } = require('child_process');
const { writeFileSync } = require('fs');
const path = require('path');

let gitTag = process.env.APP_VERSION;
if (!gitTag) {
  try {
    gitTag = execSync('git describe --tags --abbrev=0', { cwd: __dirname }).toString().trim();
  } catch (e) {
    console.warn('[set-version] git describe failed:', e.message);
    gitTag = 'dev';
  }
}

const buildDate = new Date().toISOString().split('T')[0];

const content = `// Auto-generated by set-version.js — do not edit manually.
export const appVersion = {
  version: '${gitTag}',
  buildDate: '${buildDate}',
};
`;

writeFileSync(path.join(__dirname, 'src/environments/version.ts'), content);
console.log(`[set-version] ${gitTag} | ${buildDate}`);
