name: Run API Tests with Newman

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run API tests with Newman
        run: |
          newman run users.postman_collection.json -d data.json --reporters cli,html --reporter-html-export report.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: report.html
