name: Delpoy to AH-Dev

on:
  workflow_dispatch:

concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /root
            mkdir toolshop
            cd toolshop
            git clone https://github.com/rgroetz2/practice-software-testing.git
            ls -la
          host: ${{ secrets.HOST }}
          user: githubte
          key: ${{ secrets.PRIVATE_KEY}}
