
name: Delpoy to AH-Dev

on:
  workflow_dispatch:

concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            sudo su
            cd /root
            mkdir toolshop
            cd toolshop
            git clone https://github.com/rgroetz2/practice-software-testing.git
            ls -la
          host: ${{ secrets.HOST }}
          user: githubte
          key: ${{ secrets.PRIVATE_KEY}}
